/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Menu.Visual;

import Menu.Codigo.Jugador;
import javax.swing.JOptionPane;

/**
 *
 * @author juans_000
 */
public class ChangePassword extends javax.swing.JFrame {
    
    boolean once = true, once2 = true;

    /**
     * Creates new form ChangePassword
     */
    public ChangePassword() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfPasswordV = new javax.swing.JPasswordField();
        tfPasswordN = new javax.swing.JPasswordField();
        changePas = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        bRegresar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        tfPasswordV.setFont(new java.awt.Font("Yu Mincho", 1, 18)); // NOI18N
        tfPasswordV.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfPasswordV.setText("1234567");
        tfPasswordV.setToolTipText("");
        tfPasswordV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfPasswordVMouseClicked(evt);
            }
        });
        tfPasswordV.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfPasswordVKeyTyped(evt);
            }
        });
        getContentPane().add(tfPasswordV);
        tfPasswordV.setBounds(460, 250, 110, 36);

        tfPasswordN.setFont(new java.awt.Font("Yu Mincho", 1, 18)); // NOI18N
        tfPasswordN.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfPasswordN.setText("1234567");
        tfPasswordN.setToolTipText("");
        tfPasswordN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfPasswordNMouseClicked(evt);
            }
        });
        tfPasswordN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfPasswordNKeyTyped(evt);
            }
        });
        getContentPane().add(tfPasswordN);
        tfPasswordN.setBounds(460, 300, 110, 36);

        changePas.setFont(new java.awt.Font("Pristina", 3, 24)); // NOI18N
        changePas.setText("Cambiar Password");
        changePas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                changePasMouseClicked(evt);
            }
        });
        getContentPane().add(changePas);
        changePas.setBounds(330, 350, 210, 40);

        jLabel2.setFont(new java.awt.Font("Pristina", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 0));
        jLabel2.setText("Password Nueva");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(300, 300, 150, 40);

        jLabel3.setFont(new java.awt.Font("Pristina", 3, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 0));
        jLabel3.setText("Password Vieja");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(300, 250, 150, 40);

        bRegresar.setFont(new java.awt.Font("Pristina", 3, 24)); // NOI18N
        bRegresar.setText("Regresar");
        bRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bRegresarMouseClicked(evt);
            }
        });
        getContentPane().add(bRegresar);
        bRegresar.setBounds(720, 590, 120, 37);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Menu/Visual/Menu.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 844, 629);

        jTextField1.setText("jTextField1");
        getContentPane().add(jTextField1);
        jTextField1.setBounds(480, 190, 59, 20);

        setSize(new java.awt.Dimension(860, 668));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tfPasswordNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfPasswordNMouseClicked
        if(once){
            tfPasswordN.setText("");
            once = false;
        }
    }//GEN-LAST:event_tfPasswordNMouseClicked

    private void tfPasswordNKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfPasswordNKeyTyped
        if(tfPasswordN.getPassword().length > 8)
        evt.consume();
    }//GEN-LAST:event_tfPasswordNKeyTyped

    private void changePasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changePasMouseClicked
        if(Jugador.getUsuarioActual().getPassword().equals(new String(tfPasswordV.getPassword())))
        {
            if( Jugador.getUsuarioActual().setPassword(new String(tfPasswordN.getPassword()))){
                JOptionPane.showMessageDialog(null, "Cambiado con exito!", "Notificacion", JOptionPane.INFORMATION_MESSAGE);
                new MiCuenta().setVisible(true);
                this.dispose();
            }
            else
                JOptionPane.showMessageDialog(null, "La contraseña debe tener exactamente 8 caracteres!", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else
            JOptionPane.showMessageDialog(null, "Password anterior incorrecta!", "Error", JOptionPane.ERROR_MESSAGE);
//        new MiCuenta().setVisible(true);
//        this.dispose();
    }//GEN-LAST:event_changePasMouseClicked

    private void tfPasswordVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfPasswordVMouseClicked
        if(once2){
            tfPasswordV.setText("");
            once2 = false;
        }
    }//GEN-LAST:event_tfPasswordVMouseClicked

    private void tfPasswordVKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfPasswordVKeyTyped
        if(tfPasswordV.getPassword().length > 8)
        evt.consume();
    }//GEN-LAST:event_tfPasswordVKeyTyped

    private void bRegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bRegresarMouseClicked
        new MiCuenta().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bRegresarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChangePassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bRegresar;
    private javax.swing.JButton changePas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPasswordField tfPasswordN;
    private javax.swing.JPasswordField tfPasswordV;
    // End of variables declaration//GEN-END:variables
}
