/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Menu.Visual;

import Menu.Codigo.Jugador;
import javax.swing.JOptionPane;

/**
 *
 * @author juans_000
 */
public class EliminarCuenta extends javax.swing.JFrame {

    boolean once = true;
    /**
     * Creates new form EliminarCuenta
     */
    public EliminarCuenta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfPassword = new javax.swing.JPasswordField();
        changePas = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        bRegresar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        tfPassword.setFont(new java.awt.Font("Yu Mincho", 1, 18)); // NOI18N
        tfPassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfPassword.setText("1234567");
        tfPassword.setToolTipText("");
        tfPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfPasswordMouseClicked(evt);
            }
        });
        tfPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfPasswordKeyTyped(evt);
            }
        });
        getContentPane().add(tfPassword);
        tfPassword.setBounds(440, 300, 110, 36);

        changePas.setFont(new java.awt.Font("Pristina", 3, 24)); // NOI18N
        changePas.setText("Eliminar Cuenta");
        changePas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                changePasMouseClicked(evt);
            }
        });
        getContentPane().add(changePas);
        changePas.setBounds(390, 350, 210, 40);

        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Pristina", 3, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 0));
        jLabel3.setText("seguro que quiere eliminar su cuenta");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, 20, 320, 40);

        jLabel4.setFont(new java.awt.Font("Pristina", 3, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 0, 0));
        jLabel4.setText("Escriba su contraseña si esta ");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 0, 260, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(330, 230, 310, 60);

        bRegresar.setFont(new java.awt.Font("Pristina", 3, 24)); // NOI18N
        bRegresar.setText("Regresar");
        bRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bRegresarMouseClicked(evt);
            }
        });
        getContentPane().add(bRegresar);
        bRegresar.setBounds(720, 590, 120, 37);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Menu/Visual/Menu.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 844, 629);

        setSize(new java.awt.Dimension(860, 668));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tfPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfPasswordMouseClicked
        if(once){
            tfPassword.setText("");
            once = false;
        }
    }//GEN-LAST:event_tfPasswordMouseClicked

    private void tfPasswordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfPasswordKeyTyped
        if(tfPassword.getPassword().length > 8)
        evt.consume();
    }//GEN-LAST:event_tfPasswordKeyTyped

    private void changePasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changePasMouseClicked
        if(Jugador.borrar(Jugador.getUsuarioActual().getPassword().equals(new String(tfPassword.getPassword()))))
        {
            JOptionPane.showMessageDialog(null, "Se ha Eliminado su Cuenta!!", "Notificacion", JOptionPane.INFORMATION_MESSAGE);
            new MenuInicial().setVisible(true);
            this.dispose();
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Password incorrecta!", "Error", JOptionPane.ERROR_MESSAGE);
//            new MiCuenta().setVisible(true);
        }
//        this.dispose();
    }//GEN-LAST:event_changePasMouseClicked

    private void bRegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bRegresarMouseClicked
        new MiCuenta().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bRegresarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EliminarCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EliminarCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EliminarCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EliminarCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EliminarCuenta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bRegresar;
    private javax.swing.JButton changePas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField tfPassword;
    // End of variables declaration//GEN-END:variables
}
