/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Menu.Visual;
import Menu.Codigo.Jugador;
import javax.swing.JOptionPane;

/**
 *
 * @author juans_000
 */
public class Jugar extends javax.swing.JFrame {

    /**
     * Creates new form Jugar
     */
    public Jugar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bNueva = new javax.swing.JButton();
        bCargar = new javax.swing.JButton();
        bEliminar = new javax.swing.JButton();
        bTransferir = new javax.swing.JButton();
        bMenu = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        bNueva.setFont(new java.awt.Font("Pristina", 3, 24)); // NOI18N
        bNueva.setText("Nueva Partida");
        bNueva.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bNuevaMouseClicked(evt);
            }
        });
        getContentPane().add(bNueva);
        bNueva.setBounds(390, 260, 200, 37);

        bCargar.setFont(new java.awt.Font("Pristina", 3, 24)); // NOI18N
        bCargar.setText("Cargar Partida");
        bCargar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bCargarMouseClicked(evt);
            }
        });
        getContentPane().add(bCargar);
        bCargar.setBounds(390, 320, 200, 37);

        bEliminar.setFont(new java.awt.Font("Pristina", 3, 24)); // NOI18N
        bEliminar.setText("Eliminar Partida");
        bEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bEliminarMouseClicked(evt);
            }
        });
        getContentPane().add(bEliminar);
        bEliminar.setBounds(390, 380, 200, 37);

        bTransferir.setFont(new java.awt.Font("Pristina", 3, 24)); // NOI18N
        bTransferir.setText("Transferir Partida");
        bTransferir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bTransferirMouseClicked(evt);
            }
        });
        getContentPane().add(bTransferir);
        bTransferir.setBounds(390, 440, 200, 37);

        bMenu.setFont(new java.awt.Font("Pristina", 3, 24)); // NOI18N
        bMenu.setText("Menu Principal");
        bMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bMenuMouseClicked(evt);
            }
        });
        getContentPane().add(bMenu);
        bMenu.setBounds(670, 590, 170, 37);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Menu/Visual/Menu.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 844, 629);

        setSize(new java.awt.Dimension(860, 668));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bNuevaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bNuevaMouseClicked
        new NuevaPartida().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bNuevaMouseClicked

    private void bMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bMenuMouseClicked
        new MenuPrincipal().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bMenuMouseClicked

    private void bCargarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bCargarMouseClicked
        if(Jugador.getUsuarioActual().getSaves().size() > 0)
        {
            new SavedGames().setVisible(true);
            this.dispose();
        }
        else
            JOptionPane.showMessageDialog(null, "No tienes ni una partida salvada!", "Error", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_bCargarMouseClicked

    private void bEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bEliminarMouseClicked
        new BorrarGames().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bEliminarMouseClicked

    private void bTransferirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bTransferirMouseClicked
        new TransferirGames().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bTransferirMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jugar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jugar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jugar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jugar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Jugar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCargar;
    private javax.swing.JButton bEliminar;
    private javax.swing.JButton bMenu;
    private javax.swing.JButton bNueva;
    private javax.swing.JButton bTransferir;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
