/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Menu.Visual;

import Menu.Codigo.Jugador;
import java.io.FileInputStream;
import java.io.ObjectInputStream;
import java.util.ArrayList;

/**
 *
 * @author juans_000
 */
public class MenuInicial extends javax.swing.JFrame {

    /**
     * Creates new form MenuInicial
     */
    public MenuInicial() {
        Jugador.nullEnemigo();
        initComponents();
        try
        {
            ObjectInputStream ois = new ObjectInputStream(new FileInputStream("src\\Menu\\Codigo\\players.vwg"));
            Jugador.jugadores = (ArrayList)ois.readObject();
            ois.close();
        }
        catch(Exception e)
        {
            System.out.println("No hay save!");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bLogin = new javax.swing.JButton();
        bCrearPlayer = new javax.swing.JButton();
        bExit = new javax.swing.JButton();
        menuBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(null);
        setMinimumSize(null);
        setResizable(false);
        getContentPane().setLayout(null);

        bLogin.setFont(new java.awt.Font("Pristina", 3, 24)); // NOI18N
        bLogin.setText("Login");
        bLogin.setToolTipText("");
        bLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bLoginMouseClicked(evt);
            }
        });
        getContentPane().add(bLogin);
        bLogin.setBounds(400, 260, 110, 37);

        bCrearPlayer.setFont(new java.awt.Font("Pristina", 3, 24)); // NOI18N
        bCrearPlayer.setText("Crear Player");
        bCrearPlayer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bCrearPlayerMouseClicked(evt);
            }
        });
        getContentPane().add(bCrearPlayer);
        bCrearPlayer.setBounds(380, 320, 150, 40);

        bExit.setFont(new java.awt.Font("Pristina", 3, 24)); // NOI18N
        bExit.setText("Exit");
        bExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bExitMouseClicked(evt);
            }
        });
        getContentPane().add(bExit);
        bExit.setBounds(400, 380, 110, 37);

        menuBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Menu/Visual/Menu.jpg"))); // NOI18N
        getContentPane().add(menuBackground);
        menuBackground.setBounds(0, 0, 844, 630);

        setSize(new java.awt.Dimension(860, 668));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bLoginMouseClicked
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bLoginMouseClicked

    private void bCrearPlayerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bCrearPlayerMouseClicked
        new CrearPlayer().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bCrearPlayerMouseClicked

    private void bExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bExitMouseClicked
        System.exit(1);
    }//GEN-LAST:event_bExitMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCrearPlayer;
    private javax.swing.JButton bExit;
    private javax.swing.JButton bLogin;
    private javax.swing.JLabel menuBackground;
    // End of variables declaration//GEN-END:variables
}
