/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Menu.Visual;

import Menu.Codigo.Jugador;

/**
 *
 * @author juans_000
 */
public class MiCuenta extends javax.swing.JFrame {

    /**
     * Creates new form MiCuenta
     */
    public MiCuenta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bInformacion = new javax.swing.JButton();
        bCambiarPass = new javax.swing.JButton();
        bCerrarCuenta = new javax.swing.JButton();
        bMenu = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        bInformacion.setFont(new java.awt.Font("Pristina", 3, 24)); // NOI18N
        bInformacion.setText("Ver Mi Informacion");
        bInformacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bInformacionMouseClicked(evt);
            }
        });
        getContentPane().add(bInformacion);
        bInformacion.setBounds(380, 240, 210, 37);

        bCambiarPass.setFont(new java.awt.Font("Pristina", 3, 24)); // NOI18N
        bCambiarPass.setText("Cambiar Password");
        bCambiarPass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bCambiarPassMouseClicked(evt);
            }
        });
        getContentPane().add(bCambiarPass);
        bCambiarPass.setBounds(380, 300, 210, 37);

        bCerrarCuenta.setFont(new java.awt.Font("Pristina", 3, 24)); // NOI18N
        bCerrarCuenta.setText("Cerrar Mi Cuenta");
        bCerrarCuenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bCerrarCuentaMouseClicked(evt);
            }
        });
        getContentPane().add(bCerrarCuenta);
        bCerrarCuenta.setBounds(380, 360, 210, 37);

        bMenu.setFont(new java.awt.Font("Pristina", 3, 24)); // NOI18N
        bMenu.setText("Menu Principal");
        bMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bMenuMouseClicked(evt);
            }
        });
        getContentPane().add(bMenu);
        bMenu.setBounds(670, 590, 170, 37);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Menu/Visual/Menu.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 844, 629);

        setSize(new java.awt.Dimension(860, 668));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bMenuMouseClicked
        new MenuPrincipal().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bMenuMouseClicked

    private void bInformacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bInformacionMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_bInformacionMouseClicked

    private void bCambiarPassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bCambiarPassMouseClicked
        new ChangePassword().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bCambiarPassMouseClicked

    private void bCerrarCuentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bCerrarCuentaMouseClicked
        new EliminarCuenta().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bCerrarCuentaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MiCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MiCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MiCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MiCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MiCuenta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCambiarPass;
    private javax.swing.JButton bCerrarCuenta;
    private javax.swing.JButton bInformacion;
    private javax.swing.JButton bMenu;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
