/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Menu.Visual;

import Game.Codigo.Tablero;
import Menu.Codigo.Jugador;

/**
 *
 * @author juans_000
 */
public class NuevaPartida extends javax.swing.JFrame {

    boolean once = true, once2 = true;
    public static Tablero tablero;
    /**
     * Creates new form NuevaPartida
     */
    public NuevaPartida() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfUsername = new javax.swing.JTextField();
        tfPassword = new javax.swing.JPasswordField();
        bLogin = new javax.swing.JButton();
        bRegresar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        tfUsername.setFont(new java.awt.Font("DokChampa", 1, 20)); // NOI18N
        tfUsername.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfUsername.setText("Username");
        tfUsername.setToolTipText("");
        tfUsername.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfUsernameMouseClicked(evt);
            }
        });
        getContentPane().add(tfUsername);
        tfUsername.setBounds(400, 260, 130, 32);

        tfPassword.setFont(new java.awt.Font("Yu Mincho", 1, 18)); // NOI18N
        tfPassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfPassword.setText("1234567");
        tfPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfPasswordMouseClicked(evt);
            }
        });
        tfPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfPasswordKeyTyped(evt);
            }
        });
        getContentPane().add(tfPassword);
        tfPassword.setBounds(420, 320, 90, 36);

        bLogin.setFont(new java.awt.Font("Pristina", 3, 24)); // NOI18N
        bLogin.setText("Jugar");
        bLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bLoginMouseClicked(evt);
            }
        });
        getContentPane().add(bLogin);
        bLogin.setBounds(410, 380, 110, 37);

        bRegresar.setFont(new java.awt.Font("Pristina", 3, 24)); // NOI18N
        bRegresar.setText("Regresar");
        bRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bRegresarMouseClicked(evt);
            }
        });
        getContentPane().add(bRegresar);
        bRegresar.setBounds(720, 590, 120, 37);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Menu/Visual/Menu.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 844, 629);

        setSize(new java.awt.Dimension(860, 668));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tfUsernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfUsernameMouseClicked
        if(once){
            tfUsername.setText("");
            once = false;
        }
    }//GEN-LAST:event_tfUsernameMouseClicked

    private void tfPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfPasswordMouseClicked
        if(once2){
            tfPassword.setText("");
            once2 = false;
        }
    }//GEN-LAST:event_tfPasswordMouseClicked

    private void tfPasswordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfPasswordKeyTyped
        if(tfPassword.getPassword().length > 8 )
        evt.consume();
    }//GEN-LAST:event_tfPasswordKeyTyped

    private void bLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bLoginMouseClicked
        if(Jugador.loginPlayerEnemigo(tfUsername.getText(), new String(tfPassword.getPassword())))
        {
            this.dispose();
            tablero = new Tablero();
        }
//        else
//        {
//            //JOptionPane.showMessageDialog(this, "Prueba", "Error!!!", JOptionPane.ERROR_MESSAGE);
//            new Jugar().setVisible(true);
//            this.dispose();
//        }
    }//GEN-LAST:event_bLoginMouseClicked

    private void bRegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bRegresarMouseClicked
        new Jugar().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bRegresarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevaPartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevaPartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevaPartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevaPartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NuevaPartida().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JButton bLogin;
    private javax.swing.JButton bRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField tfPassword;
    private static javax.swing.JTextField tfUsername;
    // End of variables declaration//GEN-END:variables
}
