/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Menu.Visual;

import javax.swing.JOptionPane;

/**
 *
 * @author juans_000
 */
public class Reportes extends javax.swing.JFrame {

    /**
     * Creates new form Reportes
     */
    public Reportes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bRanking = new javax.swing.JButton();
        bLogs = new javax.swing.JButton();
        bMenu = new javax.swing.JButton();
        lBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        bRanking.setFont(new java.awt.Font("Pristina", 3, 24)); // NOI18N
        bRanking.setText("Ranking");
        bRanking.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bRankingMouseClicked(evt);
            }
        });
        getContentPane().add(bRanking);
        bRanking.setBounds(410, 270, 150, 37);

        bLogs.setFont(new java.awt.Font("Pristina", 3, 24)); // NOI18N
        bLogs.setText("Logs");
        bLogs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bLogsMouseClicked(evt);
            }
        });
        getContentPane().add(bLogs);
        bLogs.setBounds(410, 330, 150, 40);

        bMenu.setFont(new java.awt.Font("Pristina", 3, 24)); // NOI18N
        bMenu.setText("Menu Principal");
        bMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bMenuMouseClicked(evt);
            }
        });
        getContentPane().add(bMenu);
        bMenu.setBounds(670, 590, 170, 37);

        lBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Menu/Visual/Menu.jpg"))); // NOI18N
        getContentPane().add(lBackground);
        lBackground.setBounds(0, 0, 844, 629);

        setSize(new java.awt.Dimension(860, 668));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bMenuMouseClicked
        new MenuPrincipal().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bMenuMouseClicked

    private void bRankingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bRankingMouseClicked
        JOptionPane.showMessageDialog(null, "La opcion estara pronto!", "Error", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_bRankingMouseClicked

    private void bLogsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bLogsMouseClicked
        JOptionPane.showMessageDialog(null, "La opcion estara pronto!", "Error", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_bLogsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reportes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bLogs;
    private javax.swing.JButton bMenu;
    private javax.swing.JButton bRanking;
    private javax.swing.JLabel lBackground;
    // End of variables declaration//GEN-END:variables
}
